### ISSUE TITLE
An error occurred when VS Code connected remotely.

### ISSUE THREAD

**Issue by lzwsoldier** [openfans-community-offical/Debian-Pi-Aarch64#152]
[21:15:30.678] Log Level: 2
[21:15:30.686] remote-ssh@0.55.0
[21:15:30.686] win32 x64
[21:15:30.689] SSH Resolver called for "ssh-remote+192.168.2.137", attempt 1
[21:15:30.689] SSH Resolver called for host: 192.168.2.137
[21:15:30.690] Setting up SSH remote "192.168.2.137"
[21:15:30.717] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[21:15:30.718] Install and start server if needed
[21:15:31.850] Checking ssh with "ssh -V"
[21:15:31.921] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[21:15:31.928] Running script with connection command: ssh -T -D 60610 192.168.2.137 bash
[21:15:31.931] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:15:32.220] > pi@192.168.2.137's password:]0;C:\WINDOWS\System32\cmd.exe
[21:15:32.220] Got some output, clearing connection timeout
[21:15:32.220] Showing password prompt
[21:15:36.584] Got password response
[21:15:36.585] "install" wrote data to terminal: "*********"
[21:15:36.605] > 
[21:15:36.764] > 64bac9872723: running
[21:15:36.849] > Acquiring lock on /home/pi/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e915
> 6c2f0c/vscode-remote-lock.pi.fcac248b077b55bae4ba5bab613fd6e9156c2f0c
[21:15:36.888] > Found existing installation at /home/pi/.vscode-server/bin/fcac248b077b55bae4ba5
> bab613fd6e9156c2f0c...
[21:15:36.929] > Found running server...
[21:15:36.946] > 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[21:15:36.979] > Checking server status on port 34075 with wget
[21:15:37.007] > 64bac9872723: start     
> sshAuthSock====
> listeningOn==34075==    
> osReleaseId==debian==   
> arch==aarch64==
> webUiAccessToken====    
> tmpDir==/run/user/1000==
> platform==linux==       
> 64bac9872723: end       
[21:15:37.008] Received install output:      
sshAuthSock====
listeningOn==34075==    
osReleaseId==debian==   
arch==aarch64==
webUiAccessToken====    
tmpDir==/run/user/1000==
platform==linux==       

[21:15:37.008] Remote server is listening on 34075
[21:15:37.008] Parsed server configuration: {"remoteListeningOn":{"port":34075},"osReleaseId":"debian","arch":"aarch64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000","platform":"linux"}
[21:15:37.008] ** Note: Support for architecture "aarch64" is in preview **
[21:15:37.010] Starting forwarding server. localPort 60620 -> socksPort 60610 -> remotePort 34075
[21:15:37.011] Forwarding server listening on 60620
[21:15:37.011] Waiting for ssh tunnel to be ready
[21:15:37.013] Tunneled 34075 to local port 60620
[21:15:37.013] Resolved "ssh-remote+192.168.2.137" to "127.0.0.1:60620"
[21:15:37.014] [Forwarding server 60620] Got connection 0
[21:15:37.026] ------

[21:15:37.034] Failed to set up socket for dynamic port forward to remote port 34075: Socket closed. Is the remote port correct?
[21:15:37.048] > channel 3: open failed: administratively prohibited: open failed
[21:15:37.052] [Forwarding server 60620] Got connection 1
[21:15:37.053] [Forwarding server 60620] Got connection 2
[21:15:37.058] Failed to set up socket for dynamic port forward to remote port 34075: Socket closed. Is the remote port correct?
[21:15:37.058] Failed to set up socket for dynamic port forward to remote port 34075: Socket closed. Is the remote port correct?
[21:15:37.062] > channel 3: open failed: administratively prohibited: open failed
> channel 4: open failed: administratively prohibited: open failed
[21:15:37.071] > 
[21:15:41.035] Unhandled rejection: Error: 没有注册配置 remote.SSH.remotePlatform，因此无法写入 用户设置。
    at k.reject (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5790:245)
    at k.resolveAndValidate (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5793:159)
    at k.doWriteConfiguration (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5787:275)
    at Object.factory (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5787:51)
    at u.consume (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:131:886
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:131:810)
    at k.writeConfiguration (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5787:36)
    at k.writeConfigurationValue (file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5813:588)
    at file:///C:/Users/lzwso/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5803:594

**Comment by aiminickwong** [comment]
Pls try the newest version.
