### ISSUE TITLE
The package "picamera" can't be successfully imported to the Python3.7. 

### ISSUE THREAD

**Issue by kaylorwu** [openfans-community-offical/Debian-Pi-Aarch64#74]
The device I used is rpi4B, and the system installed is "2019-11-30-v2019-2.0-U1-Release". 
First, I installed the picamera by the command "pip install picamera" ,then I import it to the py3.7.
But ,the pi4b gave the error as following:
_____________________________________________________________________________________
>>> import picamera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/script/picamera/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/home/pi/script/picamera/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/home/pi/script/picamera/picamera/mmal.py", line 49, in <module>
    _lib = ct.CDLL('libmmal.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmmal.so: cannot open shared object file: No such file or directory
__________________________________________________________________________________________
Then, I tried to modify the "mmal.py" script by changing the path of "libmmal.so" to "/opt/vc/lib/libmmal.so". 
The system showed the following error ：
—————————————————————————————————————
>>> import picamera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/script/picamera/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/home/pi/script/picamera/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/home/pi/script/picamera/picamera/mmal.py", line 49, in <module>
    _lib = ct.CDLL('/opt/vc/lib/libmmal.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/vc/lib/libmmal.so: wrong ELF class: ELFCLASS32
————————————————————————————————————————
I only knew this problem means that the "libmmal.so" can be applied under 32 bits system.But my rpi4B is 64 bits.
 I've tried a lot of ways but haven't found the answer.
How can I solve this problem?

**Comment by aiminickwong** [comment]
No ibmmal.so in aarch64
